name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-14, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Format
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Check
        run: deno task check

      - name: Cache dependencies
        run: deno task cache

      - name: E2E
        run: deno task e2e

      - name: Compile
        run: deno task compile
